---
title: 'Supplemental Materials: Dynamic ecosystem function during wetland salinization: differential effects on methane biogeochemistry and ecosystem productivity.'
author: Samuel D Chamberlain^1^, Elke Eichelmann^1^, Kyle S Hemes^1^, Daphne J Szutu^1^,
  Joseph G Verfaillie^1^, and Dennis D Baldocchi^1^
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: default
  word_document: default
fontsize: 12pt
header-includes:
- \usepackage{setspace}
- \doublespacing
- \usepackage{hyperref}
link-citations: yes
csl: institute-of-physics-harvard.csl
bibliography: library.bib
---

^1^Department of Environmental Science, Policy, and Management, University of California, Berkeley, California, USA

```{r setup, include=FALSE}
#setwd to main package directory
knitr::opts_knit$set(root.dir = normalizePath("../"))

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>")

knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
```

```{r packages, message=FALSE}
library(knitr)
library(tidyverse)
library(lubridate)
library(gridExtra)
library(scales)
library(zoo)
library(ggpubr)
library(entropy)
library(wq)
library(forecast)
library(stringr)
source('R/TR_functions.R'); source('R/MI_functions.R'); 
source('R/signficance_tests.R'); source('R/transformations.R')
```

# Results
```{r fig1, fig.cap="Spurious relative mutual information (*MI*) impacted by the total number of available obervations in each monthly calculation. All values presented are reshuffled in the same manner as Monte Carlo for significance testing in the main manuscript. Blue line represents a LOESS fit for the presented data.", fig.height= 5, fig.width=6, dpi=600}
#create a growing month stamp
peat6_all$month <- month(peat6_all$datetime)
peat6_all$m_yr <- paste(peat6_all$year, peat6_all$month, sep = "")

#shuffle data for comparison w/ monthly gap magnitude retained
peat6_all <- peat6_all %>%
  group_by(month) %>%
  mutate(Ta_shuf = sample(TA.x, length(TA.x), replace = F),
         wm_shuf = sample(wm, length(wm), replace = F))

#create data list by month
by_month <- peat6_all %>%
  filter(year > 2011 & year < 2018) %>%
  group_by(m_yr) %>%
  nest()

clipped_monthly <- subset(peat6_monthly, year > 2011 & year < 2018)
clipped_monthly$T_shuf <- mi_timeseries(Ta_shuf, wm_shuf, data_list = by_month)

ggplot(clipped_monthly, aes(x = CH4_obs, y = T_shuf)) +
  stat_smooth(se = F) +
  geom_point(color = "red") +
  ylab(expression(bolditalic(MI)~"("~T[air]~","~F[CH4]~")")) +
  xlab("Total methane flux observations")
```

```{r fig2, fig.cap="Monthly Kendall's rank correlation coefficient (\\tau; top panel) shared between *GEP* and *F~CH4~* (green), as well as *Ta* and *F~CH4~* (red) at the wetland that experienced salinization. The lines represent 3 month running means. Bottom panel displays daily mean water column salinity (psu).", fig.width=7, fig.height=5, dpi=600}
source("R/MI_functions.R")
source("R/signficance_tests.R")

## Processing for high salinity wetland
#create a growing month stamp
peat6_all$month <- month(peat6_all$datetime)
peat6_all$m_yr <- paste(peat6_all$year, peat6_all$month, sep = "")

#create data list by month
by_month <- peat6_all %>%
  filter(year > 2011 & year < 2018) %>%
  group_by(m_yr) %>%
  nest()

#plot that needs to be dealt with later
clipped_monthly <- subset(peat6_monthly, year > 2011 & year < 2018)
clipped_monthly$date <- as.Date(clipped_monthly$datetime)
clipped_monthly$GPP_CH4_mi <- corr_timeseries(gpp_ANNnight*-1, wm, data_list = by_month)
clipped_monthly$Tair_CH4_mi <- corr_timeseries(TA.x, wm, data_list = by_month)

a <- ggplot(clipped_monthly) +
  geom_point(aes(x = date, y = Tair_CH4_mi), color = "red", alpha = 0.5) +
  geom_line(aes(x = date, y = ma(Tair_CH4_mi, 3)), color = "red", size = 1) +
  geom_point(aes(x = date, y = GPP_CH4_mi), color = "dark green", alpha = 0.5) +
  geom_line(aes(x = date, y = ma(GPP_CH4_mi, 3)), color = "dark green", size = 1) +  
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  ylab(expression(tau~"(x,"~F[CH4]~")")) + xlab("") + ggtitle("Rising salinity wetland") +
  theme_bw()

b <- ggplot(subset(peat6_daily, year > 2011 & year < 2018), aes(x=as.Date(datetime), y=Sal)) +
  geom_line(color = "blue") +
  scale_y_continuous(limits = c(0, 7)) +
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  ylab("Salinity (psu)") + xlab("Year") +
  theme_bw()

#Multiple plots aligned
iA <- ggplotGrob(a)
iB <- ggplotGrob(b)

maxWidth = grid::unit.pmax(iA$widths[2:5], iB$widths[2:5])
iA$widths[2:5] <- as.list(maxWidth); iB$widths[2:5] <- as.list(maxWidth); 

grid.arrange(iA, iB, ncol=1)
```

```{r fig3, fig.cap="Time series of daily methane fluxes (*F~CH4~*), gross ecosystem photosynthesis (*GEP*), net ecosystem exchange (*NEE*), and salinity at the reference wetland and the wetland that experienced salinization.", fig.height = 5, fig.width = 7, dpi=600}
time_series <- theme_bw() +
  theme(panel.grid.minor=element_blank(), panel.grid.major.y = element_blank(),
        axis.title.x = element_blank(), axis.title.y = element_text(size=9))

both_sites <- subset(rbind(peat19_daily, peat6_daily), year > 2011)
both_sites$date <- as.Date(both_sites$datetime)

a <- ggplot(both_sites, aes(x=date, y=mgCH4, color=site)) +
  geom_line(size = 0.5) + 
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  ylab(expression(F[CH4]~" "~"("~mg~C~m^{-2}~d^{-1}~")")) + 
  time_series +
  theme(legend.title=element_blank(), legend.margin = margin(0, 0, 0, 0),
        legend.position=c(.85, .80),
        legend.key.size =  unit(0.2, "in"), legend.text = element_text(size=8),
        legend.background = element_rect(fill = "transparent"))

b <- ggplot(both_sites, aes(x=date, y=gGEP, color=site)) +
  geom_line(size = 0.5) +
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  time_series + theme(legend.position = "none")

c <- ggplot(both_sites, aes(x=date, y=gCO2, color=site)) +
  geom_line(size = 0.5) +
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  time_series + theme(legend.position = "none")

d <- ggplot(both_sites, aes(x=date, y=Sal, color=site)) +
  geom_line() + 
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  time_series + theme(legend.position = "none")

#Multiple plots aligned
iA <- ggplotGrob(a)
iB <- ggplotGrob(b)
iC <- ggplotGrob(c)
iD <- ggplotGrob(d)


maxWidth = grid::unit.pmax(iA$widths[2:5], iB$widths[2:5], iC$widths[2:5], iD$widths[2:5])
iA$widths[2:5] <- as.list(maxWidth); iB$widths[2:5] <- as.list(maxWidth); 
iC$widths[2:5] <- as.list(maxWidth); iD$widths[2:5] <- as.list(maxWidth); 

grid.arrange(iA, iB, iC, iD, ncol=1)
```

```{r fig4, fig.cap="Relative transfer entropy (***TE***) from (top panel) *Ta* to *F~CH4~* and (bottom panel) *F~CH4~* to *Ta* over multiple growing seasons (DOY 100-300). The red line represents significance threshold (*P* < 0.05) based on Monte Carlo reshuffling of the time series. Based on *a priori* knowledge changes in *Ta* should induce changes in *F~CH4~*, but not vice versa.", fig.height=4, fig.width=7.5, dpi=600}

#apply anomaly filter
anom_data <- peat6_all %>%
  arrange(year, time) %>%
  mutate(CH4_anom = anom_filter(wm_gf),
         TA_anom = anom_filter(TA.x),
         GPP_anom = anom_filter(gpp_ANNnight))

anom_data <- arrange(anom_data, datetime)
anom_data$CH4na_anom <- ifelse(is.na(anom_data$wm), NA, anom_data$CH4_anom) # re-insert missing values

# Focus only on high v. low salinity years without additional disturbance
# other disturbance includes the 2014 insect outbreak and 2017 flushing events
anom_data <- subset(anom_data, year %in% c(2012, 2013, 2015, 2016))

#create data list by annual growing season
by_year <- anom_data %>%
  filter(DOY > 100 & DOY < 300) %>%
  group_by(year) %>%
  nest()

#calculate lagged transfer entropy time series (up to 2 day lag at half-hourly timestep)
# for TA -> CH4
tr_wm_ta <- tr_timeseries(TA_anom, CH4na_anom, data_list = by_year, type = "observed", 
                           lags = 72, bins = 10, normalize = T)

mc_wm_ta <- tr_timeseries(TA_anom, CH4na_anom, data_list = by_year, type = "shuffled", 
                           lags = 72, bins = 10, runs = 25, alpha = 0.05, normalize = T)
# for CH4 -> TA
tr_ta_wm <- tr_timeseries(CH4na_anom, TA_anom, data_list = by_year, type = "observed", 
                           lags = 72, bins = 10, normalize = T)

mc_ta_wm <- tr_timeseries(CH4na_anom, TA_anom, data_list = by_year, type = "shuffled", 
                           lags = 72, bins = 10, runs = 25, alpha = 0.05, normalize = T)

#unlist data to tidy dataframe
wm.ta_df <- tidy_list(tr_ta_wm); wm.ta_shuf <- tidy_list(mc_ta_wm)
ta.wm_df <- tidy_list(tr_wm_ta); ta.wm_shuf <- tidy_list(mc_wm_ta)

a <- ggplot() +
  geom_line(data = ta.wm_df, aes(x = hour, y = tr)) +
  geom_line(data = ta.wm_shuf, aes(x = hour, y = tr), color = "red") +
  facet_wrap(~year, nrow = 1) +
  scale_x_continuous(breaks = seq(0, 48, by = 6)) +
  scale_y_continuous(limits = c(0, 0.04)) +
  ylab(expression(bolditalic(TE)~"("~T[a] %->% F[CH4]~")"))

b <- ggplot() +
  geom_line(data = wm.ta_df, aes(x = hour, y = tr)) +
  geom_line(data = wm.ta_shuf, aes(x = hour, y = tr), color = "red") +
  facet_wrap(~year, nrow = 1) +
  scale_x_continuous(breaks = seq(0, 48, by = 6)) +
  scale_y_continuous(limits = c(0, 0.04)) +
  xlab("Lag (hours)")  + ylab(expression(bolditalic(TE)~"("~F[CH4] %->% T[a]~")"))

#Multiple plots aligned
iA <- ggplotGrob(a)
iB <- ggplotGrob(b)

maxWidth = grid::unit.pmax(iA$widths[2:5], iB$widths[2:5])
iA$widths[2:5] <- as.list(maxWidth); iB$widths[2:5] <- as.list(maxWidth); 

grid.arrange(iA, iB, ncol=1)
```

```{r fig5, fig.cap="Relative transfer entropy (***TE***) from (top panel) *GEP* to *F~CH4~* and (bottom panel) *F~CH4~* to *GEP* over multiple growing seasons (DOY 100-300). The red line represents significance threshold (*P* < 0.05) based on Monte Carlo reshuffling of the time series.", fig.height=4, fig.width=7.5, dpi=600}

#calculate lagged transfer entropy time series (up to 2 day lag at half-hourly timestep)
# for TA -> CH4
tr_wm_gep <- tr_timeseries(GPP_anom, CH4na_anom, data_list = by_year, type = "observed", 
                           lags = 72, bins = 10, normalize = T)

mc_wm_gep <- tr_timeseries(GPP_anom, CH4na_anom, data_list = by_year, type = "shuffled", 
                           lags = 72, bins = 10, runs = 5, alpha = 0.05, normalize = T)
# for CH4 -> TA
tr_gep_wm <- tr_timeseries(CH4na_anom, GPP_anom, data_list = by_year, type = "observed", 
                           lags = 72, bins = 10, normalize = T)

mc_gep_wm <- tr_timeseries(CH4na_anom, GPP_anom, data_list = by_year, type = "shuffled", 
                           lags = 72, bins = 10, runs = 5, alpha = 0.05, normalize = T)

#unlist data to tidy dataframe
wm.gep_df <- tidy_list(tr_gep_wm); wm.gep_shuf <- tidy_list(mc_gep_wm)
gep.wm_df <- tidy_list(tr_wm_gep); gep.wm_shuf <- tidy_list(mc_wm_gep)

a <- ggplot() +
  geom_line(data = gep.wm_df, aes(x = hour, y = tr)) +
  geom_line(data = gep.wm_shuf, aes(x = hour, y = tr), color = "red") +
  facet_wrap(~year, nrow = 1) +
  scale_x_continuous(breaks = seq(0, 48, by = 6)) +
  scale_y_continuous(limits = c(0, 0.04)) +
  ylab(expression(bolditalic(TE)~"("~GEP %->% F[CH4]~")"))

b <- ggplot() +
  geom_line(data = wm.gep_df, aes(x = hour, y = tr)) +
  geom_line(data = wm.gep_shuf, aes(x = hour, y = tr), color = "red") +
  facet_wrap(~year, nrow = 1) +
  scale_x_continuous(breaks = seq(0, 48, by = 6)) +
  scale_y_continuous(limits = c(0, 0.04)) +
  xlab("Lag (hours)")  + ylab(expression(bolditalic(TE)~"("~F[CH4] %->% GEP~")"))

#Multiple plots aligned
iA <- ggplotGrob(a)
iB <- ggplotGrob(b)

maxWidth = grid::unit.pmax(iA$widths[2:5], iB$widths[2:5])
iA$widths[2:5] <- as.list(maxWidth); iB$widths[2:5] <- as.list(maxWidth); 

grid.arrange(iA, iB, ncol=1)
```
